# name: CI - Infrastructure

# on:
#   pull_request:
#     paths:
#       - 'infra/**'
#   push:
#     branches: ['**']
#     paths:
#       - 'infra/**'
#       - '.github/workflows/ci_infra.yaml'

# jobs:
#   infra-ci:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v3
#         with:
#           terraform_version: '1.4.0'

#       - name: Terraform fmt check
#         working-directory: ./infra
#         run: terraform fmt -check -recursive

#       - name: Terraform validate
#         working-directory: ./infra
#         run: terraform validate
